# Generated by Django 4.1.4 on 2022-12-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_ordered_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='in_cart',
            new_name='orders',
        ),
    ]
